import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { type ReactNode } from "react";
import clsx from "clsx";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

interface Language {
  lang: string;
}

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'de' }]
}
//TODO: Perhaps generate the paths first and then work on the middleware.
// also render the countries in the header.

export default function RootLayout({
  children,
  params
}: {
  children: ReactNode;
  params: Language
}) {
  return (
    <html lang={params.lang} className={clsx('bg-gray-50 antialiased', inter.variable)}>
    <body>{children}</body>
    </html>
  );
}
